#! usr/bin/bash

list_tables(){
read -r cmd
cmd=$(echo "$cmd" | tr '[:upper:]' '[:lower:]')
set -- $cmd
count=$#

if [[ "$count" -eq 2 ]]
then
  if [[ "$1" == "show" && "$2" == "tables" ]]
  then
   ls ./
  else
   echo syntax error,
  fi
else
  echo error, check your syntax,
fi
}
