#! /usr/bin/bash

#source ~/final_bash_project/table_menu

connecting_database() {

    mode="$1"   # menu OR sql

    echo "Connecting to Database"

    if [[ "$mode" == "menu" ]]
    then
        echo "Enter database name: "
        read db
        
    else
        db="$2"
    fi


    if [ -d "./dbms/$db" ]; then
       
         cd "./dbms/$db" 2> /dev/null || { echo "Error opening $db"; exit; }  
         echo "Connected to : $db"

         
         source ~/final_bash_project/table_menu "$db"
         #exec bash
         
         cd -  
    else
        echo "$db doesn't exist !!!"
    fi
}

#connecting_database
