#! /usr/bin/bash


connecting_database() {

    echo "Connecting to Database"
    echo "Enter database name: "
    read db 2> /dev/null
    
    if [ -d "./DBMS/$db" ]; then
       
        cd "./DBMS/$db" 2> /dev/null || { echo "Error opening $db"; exit; }
         
         echo "Connected to : $db"
        
       table_menu $db
        
        cd -  
    else
        echo "$db doesn't exist !!!"
    fi
}


table_menu() {
    local db=$1
    while true; do
        echo "----------------------------------"
        echo "Database $db menu"
        echo '----------------------------------'
        echo "1.Create Table"
        echo "2.List Tables"
        echo "3.Select From Table"
        echo "4.Insert into Table"
        echo "5.Update Table"
        echo "6.Delete From Table"
        echo "7.Delete Table"
        echo "8.Exit"
        read -r -p'Enter your option ' opt
        case $opt in
            1) create_table $db ;;
            2) list_tables  ;;   
            3) select_from_table $db ;;
            4) insert_into_table $db ;;
            5) update_table $db ;;
            6) delete_from_table $db ;;
            7) delete_table $db ;;
            8) break ;;   
            *) echo "Incorrect option !!!" 
		     sleep 2 ;;
        esac
         
    done
}

