#! /usr/bin/bash

drop_db(){
	read  -r -p "Enter DB name: " db


	if  [[ ! -d "./DBMS/$db" ]]; then
		echo "Not Found $db"
		return 1
	else
		rm -r ./DBMS/$db
		echo "$db was deleted successfully"
		
	fi

}	
	
