#! usr/bin/bash

drop_table(){
read -r cmd
cmd=$(echo "$cmd" | tr '[:upper:]' '[:lower:]')
set -- $cmd
count=$#
drop=$3

if [[ "$count" -eq 3 ]]
then
  if [[ "$1" == "drop" && "$2" == "table" ]]
  then
   rm -r $drop
   echo table dropped successfully,
  else
   echo syntax error,
  fi
else
  echo check your syntax,
fi
}
